# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_BITCOINSIMPLECERT = descriptor.Descriptor(
  name='BitcoinSimpleCert',
  full_name='bitcoincert.BitcoinSimpleCert',
  filename='cert.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ecdsa_pubkeys', full_name='bitcoincert.BitcoinSimpleCert.ecdsa_pubkeys', index=0,
      number=1, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='SSL_cert', full_name='bitcoincert.BitcoinSimpleCert.SSL_cert', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='email', full_name='bitcoincert.BitcoinSimpleCert.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='bitcoincert.BitcoinSimpleCert.url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class BitcoinSimpleCert(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BITCOINSIMPLECERT

